// Generated by delombok at Sat Sep 17 17:47:34 PDT 2022
package com.quintrix.jepsen.erik.sixth.model;

public class Department {
  private String deptName;
  private Integer deptNumber;

  public String getDeptName() {
    return this.deptName;
  }

  public Integer getDeptNumber() {
    return this.deptNumber;
  }

  public void setDeptName(final String deptName) {
    this.deptName = deptName;
  }

  public void setDeptNumber(final Integer deptNumber) {
    this.deptNumber = deptNumber;
  }

  public boolean equals(final java.lang.Object o) {
    if (o == this)
      return true;
    if (!(o instanceof Department))
      return false;
    final Department other = (Department) o;
    if (!other.canEqual((java.lang.Object) this))
      return false;
    final java.lang.Object this$deptNumber = this.getDeptNumber();
    final java.lang.Object other$deptNumber = other.getDeptNumber();
    if (this$deptNumber == null ? other$deptNumber != null
        : !this$deptNumber.equals(other$deptNumber))
      return false;
    final java.lang.Object this$deptName = this.getDeptName();
    final java.lang.Object other$deptName = other.getDeptName();
    if (this$deptName == null ? other$deptName != null : !this$deptName.equals(other$deptName))
      return false;
    return true;
  }

  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof Department;
  }

  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $deptNumber = this.getDeptNumber();
    result = result * PRIME + ($deptNumber == null ? 43 : $deptNumber.hashCode());
    final java.lang.Object $deptName = this.getDeptName();
    result = result * PRIME + ($deptName == null ? 43 : $deptName.hashCode());
    return result;
  }

  public java.lang.String toString() {
    return "Department(deptName=" + this.getDeptName() + ", deptNumber=" + this.getDeptNumber()
        + ")";
  }

  public Department() {}

  public Department(final String deptName, final Integer deptNumber) {
    this.deptName = deptName;
    this.deptNumber = deptNumber;
  }
}
